"""
Authentic Indian Railways Operational Seed Dataset for RailETA
Includes 6 major corridors with accurate geo-coordinates, schedules,
section running times, delay propagation, and analytics metrics.
"""

from datetime import datetime
from sqlalchemy.orm import Session
from models import StationStop, Train

INITIAL_TRAINS = [
    {
        "train_number": "12951",
        "train_name": "Mumbai Central - New Delhi Tejas Rajdhani Express",
        "train_type": "Rajdhani",
        "zone": "WR / Western Railway",
        "source_code": "MMCT",
        "source_name": "Mumbai Central",
        "destination_code": "NDLS",
        "destination_name": "New Delhi",
        "running_status": "Running Late by 12m",
        "current_delay_mins": 12,
        "current_speed_kmph": 118.0,
        "max_permissible_speed_kmph": 130.0,
        "distance_covered_km": 798.0,
        "distance_remaining_km": 586.0,
        "total_distance_km": 1384.0,
        "current_lat": 24.5854,
        "current_lng": 75.8362,
        "previous_station_code": "RTM",
        "previous_station_name": "Ratlam Junction",
        "next_station_code": "KOTA",
        "next_station_name": "Kota Junction",
        "predicted_eta": "18:42",
        "prediction_range": "18:35 - 18:50",
        "prediction_confidence": 84,
        "weather_condition": "Clear / Light Haze",
        "weather_temp_c": 28.5,
        "weather_visibility_km": 9.2,
        "congestion_level": "Moderate (Kota Outer Yard)",
        "congestion_index": 0.28,
        "historical_avg_delay_mins": 11.0,
        "stops": [
            {
                "sequence": 1,
                "station_code": "MMCT",
                "station_name": "Mumbai Central",
                "platform": "1",
                "distance_km": 0.0,
                "lat": 18.9696,
                "lng": 72.8193,
                "scheduled_arrival": "17:00",
                "scheduled_departure": "17:00",
                "predicted_eta": "17:00",
                "prediction_range": "17:00 - 17:02",
                "delay_mins": 0,
                "historical_avg_delay_mins": 1.0,
                "section_scheduled_mins": 0,
                "section_predicted_mins": 0,
                "status": "Departed",
                "confidence": 99,
            },
            {
                "sequence": 2,
                "station_code": "BVI",
                "station_name": "Borivali",
                "platform": "6",
                "distance_km": 30.0,
                "lat": 19.2288,
                "lng": 72.8569,
                "scheduled_arrival": "17:22",
                "scheduled_departure": "17:24",
                "predicted_eta": "17:25",
                "prediction_range": "17:24 - 17:27",
                "delay_mins": 3,
                "historical_avg_delay_mins": 4.0,
                "section_scheduled_mins": 22,
                "section_predicted_mins": 25,
                "status": "Departed",
                "confidence": 98,
            },
            {
                "sequence": 3,
                "station_code": "ST",
                "station_name": "Surat",
                "platform": "1",
                "distance_km": 263.0,
                "lat": 21.2045,
                "lng": 72.8408,
                "scheduled_arrival": "19:43",
                "scheduled_departure": "19:48",
                "predicted_eta": "19:51",
                "prediction_range": "19:48 - 19:55",
                "delay_mins": 8,
                "historical_avg_delay_mins": 7.0,
                "section_scheduled_mins": 139,
                "section_predicted_mins": 144,
                "status": "Departed",
                "confidence": 96,
            },
            {
                "sequence": 4,
                "station_code": "BRC",
                "station_name": "Vadodara Junction",
                "platform": "2",
                "distance_km": 392.0,
                "lat": 22.3106,
                "lng": 73.1812,
                "scheduled_arrival": "21:06",
                "scheduled_departure": "21:16",
                "predicted_eta": "21:20",
                "prediction_range": "21:16 - 21:25",
                "delay_mins": 14,
                "historical_avg_delay_mins": 10.0,
                "section_scheduled_mins": 78,
                "section_predicted_mins": 84,
                "status": "Departed",
                "confidence": 95,
            },
            {
                "sequence": 5,
                "station_code": "RTM",
                "station_name": "Ratlam Junction",
                "platform": "4",
                "distance_km": 653.0,
                "lat": 23.3342,
                "lng": 75.0488,
                "scheduled_arrival": "00:25",
                "scheduled_departure": "00:28",
                "predicted_eta": "00:42",
                "prediction_range": "00:38 - 00:46",
                "delay_mins": 17,
                "historical_avg_delay_mins": 13.0,
                "section_scheduled_mins": 189,
                "section_predicted_mins": 192,
                "status": "Departed",
                "confidence": 92,
            },
            {
                "sequence": 6,
                "station_code": "KOTA",
                "station_name": "Kota Junction",
                "platform": "1",
                "distance_km": 920.0,
                "lat": 25.2238,
                "lng": 75.8806,
                "scheduled_arrival": "18:30",
                "scheduled_departure": "18:35",
                "predicted_eta": "18:42",
                "prediction_range": "18:35 - 18:50",
                "delay_mins": 12,
                "historical_avg_delay_mins": 11.0,
                "section_scheduled_mins": 165,
                "section_predicted_mins": 160,
                "status": "Approaching",
                "confidence": 84,
            },
            {
                "sequence": 7,
                "station_code": "SWM",
                "station_name": "Sawai Madhopur Junction",
                "platform": "2",
                "distance_km": 1028.0,
                "lat": 26.0173,
                "lng": 76.3526,
                "scheduled_arrival": "19:38",
                "scheduled_departure": "19:40",
                "predicted_eta": "19:47",
                "prediction_range": "19:39 - 19:56",
                "delay_mins": 9,
                "historical_avg_delay_mins": 10.0,
                "section_scheduled_mins": 63,
                "section_predicted_mins": 60,
                "status": "Upcoming",
                "confidence": 81,
            },
            {
                "sequence": 8,
                "station_code": "MTJ",
                "station_name": "Mathura Junction",
                "platform": "3",
                "distance_km": 1243.0,
                "lat": 27.4744,
                "lng": 77.6739,
                "scheduled_arrival": "21:33",
                "scheduled_departure": "21:35",
                "predicted_eta": "21:39",
                "prediction_range": "21:30 - 21:49",
                "delay_mins": 6,
                "historical_avg_delay_mins": 8.0,
                "section_scheduled_mins": 113,
                "section_predicted_mins": 110,
                "status": "Upcoming",
                "confidence": 79,
            },
            {
                "sequence": 9,
                "station_code": "NDLS",
                "station_name": "New Delhi",
                "platform": "3",
                "distance_km": 1384.0,
                "lat": 28.6429,
                "lng": 77.2191,
                "scheduled_arrival": "23:15",
                "scheduled_departure": "23:15",
                "predicted_eta": "23:19",
                "prediction_range": "23:10 - 23:28",
                "delay_mins": 4,
                "historical_avg_delay_mins": 7.0,
                "section_scheduled_mins": 100,
                "section_predicted_mins": 98,
                "status": "Upcoming",
                "confidence": 78,
            },
        ],
    },
    {
        "train_number": "22436",
        "train_name": "New Delhi - Varanasi Vande Bharat Express",
        "train_type": "Vande Bharat",
        "zone": "NR / Northern Railway",
        "source_code": "NDLS",
        "source_name": "New Delhi",
        "destination_code": "BSB",
        "destination_name": "Varanasi Junction",
        "running_status": "On Time",
        "current_delay_mins": 2,
        "current_speed_kmph": 128.0,
        "max_permissible_speed_kmph": 130.0,
        "distance_covered_km": 442.0,
        "distance_remaining_km": 317.0,
        "total_distance_km": 759.0,
        "current_lat": 26.4499,
        "current_lng": 80.3319,
        "previous_station_code": "CNB",
        "previous_station_name": "Kanpur Central",
        "next_station_code": "PRYJ",
        "next_station_name": "Prayagraj Junction",
        "predicted_eta": "12:10",
        "prediction_range": "12:07 - 12:14",
        "prediction_confidence": 93,
        "weather_condition": "Sunny & Clear",
        "weather_temp_c": 31.0,
        "weather_visibility_km": 10.0,
        "congestion_level": "Low (Green Corridor)",
        "congestion_index": 0.14,
        "historical_avg_delay_mins": 4.0,
        "stops": [
            {
                "sequence": 1,
                "station_code": "NDLS",
                "station_name": "New Delhi",
                "platform": "16",
                "distance_km": 0.0,
                "lat": 28.6429,
                "lng": 77.2191,
                "scheduled_arrival": "06:00",
                "scheduled_departure": "06:00",
                "predicted_eta": "06:00",
                "prediction_range": "06:00 - 06:01",
                "delay_mins": 0,
                "historical_avg_delay_mins": 1.0,
                "section_scheduled_mins": 0,
                "section_predicted_mins": 0,
                "status": "Departed",
                "confidence": 99,
            },
            {
                "sequence": 2,
                "station_code": "CNB",
                "station_name": "Kanpur Central",
                "platform": "1",
                "distance_km": 440.0,
                "lat": 26.4539,
                "lng": 80.3512,
                "scheduled_arrival": "10:08",
                "scheduled_departure": "10:10",
                "predicted_eta": "10:11",
                "prediction_range": "10:09 - 10:13",
                "delay_mins": 3,
                "historical_avg_delay_mins": 4.0,
                "section_scheduled_mins": 248,
                "section_predicted_mins": 251,
                "status": "Departed",
                "confidence": 96,
            },
            {
                "sequence": 3,
                "station_code": "PRYJ",
                "station_name": "Prayagraj Junction",
                "platform": "6",
                "distance_km": 635.0,
                "lat": 25.4448,
                "lng": 81.8290,
                "scheduled_arrival": "12:08",
                "scheduled_departure": "12:10",
                "predicted_eta": "12:10",
                "prediction_range": "12:07 - 12:14",
                "delay_mins": 2,
                "historical_avg_delay_mins": 5.0,
                "section_scheduled_mins": 118,
                "section_predicted_mins": 117,
                "status": "Approaching",
                "confidence": 93,
            },
            {
                "sequence": 4,
                "station_code": "BSB",
                "station_name": "Varanasi Junction",
                "platform": "1",
                "distance_km": 759.0,
                "lat": 25.3273,
                "lng": 82.9859,
                "scheduled_arrival": "14:00",
                "scheduled_departure": "14:00",
                "predicted_eta": "13:59",
                "prediction_range": "13:55 - 14:05",
                "delay_mins": -1,
                "historical_avg_delay_mins": 3.0,
                "section_scheduled_mins": 110,
                "section_predicted_mins": 107,
                "status": "Upcoming",
                "confidence": 91,
            },
        ],
    },
    {
        "train_number": "12301",
        "train_name": "Howrah - New Delhi Rajdhani Express (via Gaya)",
        "train_type": "Rajdhani",
        "zone": "ER / Eastern Railway",
        "source_code": "HWH",
        "source_name": "Howrah Junction",
        "destination_code": "NDLS",
        "destination_name": "New Delhi",
        "running_status": "Running Late by 24m",
        "current_delay_mins": 24,
        "current_speed_kmph": 104.0,
        "max_permissible_speed_kmph": 130.0,
        "distance_covered_km": 668.0,
        "distance_remaining_km": 783.0,
        "total_distance_km": 1451.0,
        "current_lat": 25.2817,
        "current_lng": 83.1194,
        "previous_station_code": "GAYA",
        "previous_station_name": "Gaya Junction",
        "next_station_code": "DDU",
        "next_station_name": "Pt. DD Upadhyaya Junction",
        "predicted_eta": "01:49",
        "prediction_range": "01:42 - 01:58",
        "prediction_confidence": 81,
        "weather_condition": "Mist / High Humidity",
        "weather_temp_c": 24.0,
        "weather_visibility_km": 5.4,
        "congestion_level": "High (Mughalsarai Yard)",
        "congestion_index": 0.56,
        "historical_avg_delay_mins": 19.0,
        "stops": [
            {
                "sequence": 1,
                "station_code": "HWH",
                "station_name": "Howrah Junction",
                "platform": "9",
                "distance_km": 0.0,
                "lat": 22.5830,
                "lng": 88.3426,
                "scheduled_arrival": "16:50",
                "scheduled_departure": "16:50",
                "predicted_eta": "16:50",
                "prediction_range": "16:50 - 16:52",
                "delay_mins": 0,
                "historical_avg_delay_mins": 1.0,
                "section_scheduled_mins": 0,
                "section_predicted_mins": 0,
                "status": "Departed",
                "confidence": 99,
            },
            {
                "sequence": 2,
                "station_code": "DHN",
                "station_name": "Dhanbad Junction",
                "platform": "2",
                "distance_km": 259.0,
                "lat": 23.7913,
                "lng": 86.4299,
                "scheduled_arrival": "19:55",
                "scheduled_departure": "20:00",
                "predicted_eta": "20:09",
                "prediction_range": "20:05 - 20:13",
                "delay_mins": 14,
                "historical_avg_delay_mins": 9.0,
                "section_scheduled_mins": 185,
                "section_predicted_mins": 199,
                "status": "Departed",
                "confidence": 95,
            },
            {
                "sequence": 3,
                "station_code": "GAYA",
                "station_name": "Gaya Junction",
                "platform": "1",
                "distance_km": 458.0,
                "lat": 24.8037,
                "lng": 84.9994,
                "scheduled_arrival": "22:19",
                "scheduled_departure": "22:22",
                "predicted_eta": "22:45",
                "prediction_range": "22:40 - 22:50",
                "delay_mins": 26,
                "historical_avg_delay_mins": 15.0,
                "section_scheduled_mins": 139,
                "section_predicted_mins": 151,
                "status": "Departed",
                "confidence": 92,
            },
            {
                "sequence": 4,
                "station_code": "DDU",
                "station_name": "Pt. DD Upadhyaya Junction",
                "platform": "4",
                "distance_km": 661.0,
                "lat": 25.2785,
                "lng": 83.1197,
                "scheduled_arrival": "01:25",
                "scheduled_departure": "01:35",
                "predicted_eta": "01:49",
                "prediction_range": "01:42 - 01:58",
                "delay_mins": 24,
                "historical_avg_delay_mins": 18.0,
                "section_scheduled_mins": 183,
                "section_predicted_mins": 181,
                "status": "Approaching",
                "confidence": 81,
            },
            {
                "sequence": 5,
                "station_code": "PRYJ",
                "station_name": "Prayagraj Junction",
                "platform": "4",
                "distance_km": 813.0,
                "lat": 25.4448,
                "lng": 81.8290,
                "scheduled_arrival": "03:15",
                "scheduled_departure": "03:17",
                "predicted_eta": "03:35",
                "prediction_range": "03:26 - 03:45",
                "delay_mins": 20,
                "historical_avg_delay_mins": 19.0,
                "section_scheduled_mins": 100,
                "section_predicted_mins": 96,
                "status": "Upcoming",
                "confidence": 79,
            },
            {
                "sequence": 6,
                "station_code": "CNB",
                "station_name": "Kanpur Central",
                "platform": "3",
                "distance_km": 1008.0,
                "lat": 26.4539,
                "lng": 80.3512,
                "scheduled_arrival": "05:20",
                "scheduled_departure": "05:25",
                "predicted_eta": "05:36",
                "prediction_range": "05:26 - 05:47",
                "delay_mins": 16,
                "historical_avg_delay_mins": 17.0,
                "section_scheduled_mins": 123,
                "section_predicted_mins": 119,
                "status": "Upcoming",
                "confidence": 77,
            },
            {
                "sequence": 7,
                "station_code": "NDLS",
                "station_name": "New Delhi",
                "platform": "12",
                "distance_km": 1451.0,
                "lat": 28.6429,
                "lng": 77.2191,
                "scheduled_arrival": "10:05",
                "scheduled_departure": "10:05",
                "predicted_eta": "10:16",
                "prediction_range": "10:05 - 10:28",
                "delay_mins": 11,
                "historical_avg_delay_mins": 14.0,
                "section_scheduled_mins": 280,
                "section_predicted_mins": 275,
                "status": "Upcoming",
                "confidence": 75,
            },
        ],
    },
    {
        "train_number": "12002",
        "train_name": "New Delhi - Rani Kamalapati Habibganj Shatabdi",
        "train_type": "Shatabdi",
        "zone": "NR / Northern Railway",
        "source_code": "NDLS",
        "source_name": "New Delhi",
        "destination_code": "RKMP",
        "destination_name": "Rani Kamalapati (Bhopal)",
        "running_status": "Running Late by 6m",
        "current_delay_mins": 6,
        "current_speed_kmph": 134.0,
        "max_permissible_speed_kmph": 150.0,
        "distance_covered_km": 318.0,
        "distance_remaining_km": 389.0,
        "total_distance_km": 707.0,
        "current_lat": 26.2183,
        "current_lng": 78.1828,
        "previous_station_code": "AGC",
        "previous_station_name": "Agra Cantt",
        "next_station_code": "GWL",
        "next_station_name": "Gwalior Junction",
        "predicted_eta": "09:29",
        "prediction_range": "09:25 - 09:34",
        "prediction_confidence": 91,
        "weather_condition": "Clear Sky",
        "weather_temp_c": 29.0,
        "weather_visibility_km": 10.0,
        "congestion_level": "Low",
        "congestion_index": 0.18,
        "historical_avg_delay_mins": 6.0,
        "stops": [
            {
                "sequence": 1,
                "station_code": "NDLS",
                "station_name": "New Delhi",
                "platform": "1",
                "distance_km": 0.0,
                "lat": 28.6429,
                "lng": 77.2191,
                "scheduled_arrival": "06:00",
                "scheduled_departure": "06:00",
                "predicted_eta": "06:00",
                "prediction_range": "06:00 - 06:02",
                "delay_mins": 0,
                "historical_avg_delay_mins": 1.0,
                "section_scheduled_mins": 0,
                "section_predicted_mins": 0,
                "status": "Departed",
                "confidence": 99,
            },
            {
                "sequence": 2,
                "station_code": "AGC",
                "station_name": "Agra Cantt",
                "platform": "1",
                "distance_km": 195.0,
                "lat": 27.1578,
                "lng": 77.9899,
                "scheduled_arrival": "07:50",
                "scheduled_departure": "07:55",
                "predicted_eta": "07:58",
                "prediction_range": "07:55 - 08:01",
                "delay_mins": 8,
                "historical_avg_delay_mins": 6.0,
                "section_scheduled_mins": 110,
                "section_predicted_mins": 118,
                "status": "Departed",
                "confidence": 96,
            },
            {
                "sequence": 3,
                "station_code": "GWL",
                "station_name": "Gwalior Junction",
                "platform": "1",
                "distance_km": 313.0,
                "lat": 26.2156,
                "lng": 78.1818,
                "scheduled_arrival": "09:23",
                "scheduled_departure": "09:28",
                "predicted_eta": "09:29",
                "prediction_range": "09:25 - 09:34",
                "delay_mins": 6,
                "historical_avg_delay_mins": 7.0,
                "section_scheduled_mins": 88,
                "section_predicted_mins": 86,
                "status": "Approaching",
                "confidence": 91,
            },
            {
                "sequence": 4,
                "station_code": "VGLJ",
                "station_name": "Virangana Lakshmibai Jhansi",
                "platform": "2",
                "distance_km": 411.0,
                "lat": 25.4484,
                "lng": 78.5685,
                "scheduled_arrival": "10:45",
                "scheduled_departure": "10:53",
                "predicted_eta": "10:49",
                "prediction_range": "10:44 - 10:55",
                "delay_mins": 4,
                "historical_avg_delay_mins": 6.0,
                "section_scheduled_mins": 77,
                "section_predicted_mins": 75,
                "status": "Upcoming",
                "confidence": 89,
            },
            {
                "sequence": 5,
                "station_code": "RKMP",
                "station_name": "Rani Kamalapati (Bhopal)",
                "platform": "1",
                "distance_km": 707.0,
                "lat": 23.2167,
                "lng": 77.4385,
                "scheduled_arrival": "14:40",
                "scheduled_departure": "14:40",
                "predicted_eta": "14:42",
                "prediction_range": "14:36 - 14:49",
                "delay_mins": 2,
                "historical_avg_delay_mins": 5.0,
                "section_scheduled_mins": 227,
                "section_predicted_mins": 225,
                "status": "Upcoming",
                "confidence": 88,
            },
        ],
    },
    {
        "train_number": "12627",
        "train_name": "KSR Bengaluru - New Delhi Karnataka Express",
        "train_type": "Superfast",
        "zone": "SWR / South Western",
        "source_code": "SBC",
        "source_name": "KSR Bengaluru City",
        "destination_code": "NDLS",
        "destination_name": "New Delhi",
        "running_status": "Running Late by 31m",
        "current_delay_mins": 31,
        "current_speed_kmph": 92.0,
        "max_permissible_speed_kmph": 110.0,
        "distance_covered_km": 1340.0,
        "distance_remaining_km": 1070.0,
        "total_distance_km": 2410.0,
        "current_lat": 21.1458,
        "current_lng": 79.0882,
        "previous_station_code": "BPQ",
        "previous_station_name": "Balharshah Junction",
        "next_station_code": "NGP",
        "next_station_name": "Nagpur Junction",
        "predicted_eta": "16:38",
        "prediction_range": "16:28 - 16:49",
        "prediction_confidence": 79,
        "weather_condition": "Light Rain Showers",
        "weather_temp_c": 26.0,
        "weather_visibility_km": 6.8,
        "congestion_level": "Moderate-High (Nagpur Diamond Crossing)",
        "congestion_index": 0.44,
        "historical_avg_delay_mins": 24.0,
        "stops": [
            {
                "sequence": 1,
                "station_code": "SBC",
                "station_name": "KSR Bengaluru City",
                "platform": "1",
                "distance_km": 0.0,
                "lat": 12.9781,
                "lng": 77.5695,
                "scheduled_arrival": "19:20",
                "scheduled_departure": "19:20",
                "predicted_eta": "19:20",
                "prediction_range": "19:20 - 19:22",
                "delay_mins": 0,
                "historical_avg_delay_mins": 2.0,
                "section_scheduled_mins": 0,
                "section_predicted_mins": 0,
                "status": "Departed",
                "confidence": 99,
            },
            {
                "sequence": 2,
                "station_code": "GTL",
                "station_name": "Guntakal Junction",
                "platform": "3",
                "distance_km": 280.0,
                "lat": 15.1669,
                "lng": 77.3765,
                "scheduled_arrival": "00:05",
                "scheduled_departure": "00:10",
                "predicted_eta": "00:22",
                "prediction_range": "00:18 - 00:26",
                "delay_mins": 17,
                "historical_avg_delay_mins": 14.0,
                "section_scheduled_mins": 285,
                "section_predicted_mins": 302,
                "status": "Departed",
                "confidence": 95,
            },
            {
                "sequence": 3,
                "station_code": "BPQ",
                "station_name": "Balharshah Junction",
                "platform": "2",
                "distance_km": 1190.0,
                "lat": 19.8511,
                "lng": 79.3499,
                "scheduled_arrival": "12:50",
                "scheduled_departure": "12:55",
                "predicted_eta": "13:29",
                "prediction_range": "13:24 - 13:34",
                "delay_mins": 34,
                "historical_avg_delay_mins": 26.0,
                "section_scheduled_mins": 760,
                "section_predicted_mins": 777,
                "status": "Departed",
                "confidence": 90,
            },
            {
                "sequence": 4,
                "station_code": "NGP",
                "station_name": "Nagpur Junction",
                "platform": "1",
                "distance_km": 1401.0,
                "lat": 21.1522,
                "lng": 79.0888,
                "scheduled_arrival": "16:07",
                "scheduled_departure": "16:12",
                "predicted_eta": "16:38",
                "prediction_range": "16:28 - 16:49",
                "delay_mins": 31,
                "historical_avg_delay_mins": 24.0,
                "section_scheduled_mins": 192,
                "section_predicted_mins": 189,
                "status": "Approaching",
                "confidence": 79,
            },
            {
                "sequence": 5,
                "station_code": "BPL",
                "station_name": "Bhopal Junction",
                "platform": "2",
                "distance_km": 1791.0,
                "lat": 23.2685,
                "lng": 77.4126,
                "scheduled_arrival": "22:20",
                "scheduled_departure": "22:30",
                "predicted_eta": "22:45",
                "prediction_range": "22:34 - 22:58",
                "delay_mins": 25,
                "historical_avg_delay_mins": 22.0,
                "section_scheduled_mins": 368,
                "section_predicted_mins": 362,
                "status": "Upcoming",
                "confidence": 76,
            },
            {
                "sequence": 6,
                "station_code": "NDLS",
                "station_name": "New Delhi",
                "platform": "5",
                "distance_km": 2410.0,
                "lat": 28.6429,
                "lng": 77.2191,
                "scheduled_arrival": "09:00",
                "scheduled_departure": "09:00",
                "predicted_eta": "09:18",
                "prediction_range": "09:05 - 09:32",
                "delay_mins": 18,
                "historical_avg_delay_mins": 20.0,
                "section_scheduled_mins": 630,
                "section_predicted_mins": 623,
                "status": "Upcoming",
                "confidence": 74,
            },
        ],
    },
    {
        "train_number": "20607",
        "train_name": "MGR Chennai Central - Mysuru Vande Bharat Express",
        "train_type": "Vande Bharat",
        "zone": "SR / Southern Railway",
        "source_code": "MAS",
        "source_name": "MGR Chennai Central",
        "destination_code": "MYS",
        "destination_name": "Mysuru Junction",
        "running_status": "On Time",
        "current_delay_mins": 0,
        "current_speed_kmph": 115.0,
        "max_permissible_speed_kmph": 130.0,
        "distance_covered_km": 295.0,
        "distance_remaining_km": 202.0,
        "total_distance_km": 497.0,
        "current_lat": 12.9767,
        "current_lng": 77.5713,
        "previous_station_code": "KPD",
        "previous_station_name": "Katpadi Junction",
        "next_station_code": "SBC",
        "next_station_name": "KSR Bengaluru City",
        "predicted_eta": "10:15",
        "prediction_range": "10:12 - 10:18",
        "prediction_confidence": 95,
        "weather_condition": "Pleasant & Clear",
        "weather_temp_c": 26.5,
        "weather_visibility_km": 10.0,
        "congestion_level": "Low",
        "congestion_index": 0.12,
        "historical_avg_delay_mins": 2.0,
        "stops": [
            {
                "sequence": 1,
                "station_code": "MAS",
                "station_name": "MGR Chennai Central",
                "platform": "7",
                "distance_km": 0.0,
                "lat": 13.0827,
                "lng": 80.2707,
                "scheduled_arrival": "05:50",
                "scheduled_departure": "05:50",
                "predicted_eta": "05:50",
                "prediction_range": "05:50 - 05:51",
                "delay_mins": 0,
                "historical_avg_delay_mins": 1.0,
                "section_scheduled_mins": 0,
                "section_predicted_mins": 0,
                "status": "Departed",
                "confidence": 99,
            },
            {
                "sequence": 2,
                "station_code": "KPD",
                "station_name": "Katpadi Junction",
                "platform": "1",
                "distance_km": 130.0,
                "lat": 12.9698,
                "lng": 79.1381,
                "scheduled_arrival": "07:23",
                "scheduled_departure": "07:25",
                "predicted_eta": "07:24",
                "prediction_range": "07:22 - 07:26",
                "delay_mins": 1,
                "historical_avg_delay_mins": 2.0,
                "section_scheduled_mins": 93,
                "section_predicted_mins": 94,
                "status": "Departed",
                "confidence": 97,
            },
            {
                "sequence": 3,
                "station_code": "SBC",
                "station_name": "KSR Bengaluru City",
                "platform": "8",
                "distance_km": 359.0,
                "lat": 12.9781,
                "lng": 77.5695,
                "scheduled_arrival": "10:15",
                "scheduled_departure": "10:20",
                "predicted_eta": "10:15",
                "prediction_range": "10:12 - 10:18",
                "delay_mins": 0,
                "historical_avg_delay_mins": 3.0,
                "section_scheduled_mins": 170,
                "section_predicted_mins": 169,
                "status": "Approaching",
                "confidence": 95,
            },
            {
                "sequence": 4,
                "station_code": "MYS",
                "station_name": "Mysuru Junction",
                "platform": "1",
                "distance_km": 497.0,
                "lat": 12.3168,
                "lng": 76.6445,
                "scheduled_arrival": "12:20",
                "scheduled_departure": "12:20",
                "predicted_eta": "12:18",
                "prediction_range": "12:14 - 12:23",
                "delay_mins": -2,
                "historical_avg_delay_mins": 2.0,
                "section_scheduled_mins": 120,
                "section_predicted_mins": 118,
                "status": "Upcoming",
                "confidence": 94,
            },
        ],
    },
]

ANALYTICS_SUMMARY = {
    "kpis": {
        "network_mae_mins": 3.4,
        "prediction_accuracy_pct": 94.2,
        "active_trains_monitored": 1840,
        "avg_recovery_saved_mins": 8.6,
    },
    "scheduled_vs_actual": [
        {"station": "MMCT", "scheduled_mins": 0, "actual_mins": 0, "predicted_mins": 0},
        {"station": "BVI", "scheduled_mins": 22, "actual_mins": 25, "predicted_mins": 24},
        {"station": "ST", "scheduled_mins": 163, "actual_mins": 171, "predicted_mins": 170},
        {"station": "BRC", "scheduled_mins": 246, "actual_mins": 260, "predicted_mins": 258},
        {"station": "RTM", "scheduled_mins": 445, "actual_mins": 462, "predicted_mins": 460},
        {"station": "KOTA", "scheduled_mins": 610, "actual_mins": 622, "predicted_mins": 622},
        {"station": "SWM", "scheduled_mins": 678, "actual_mins": 688, "predicted_mins": 687},
        {"station": "MTJ", "scheduled_mins": 793, "actual_mins": 800, "predicted_mins": 799},
        {"station": "NDLS", "scheduled_mins": 895, "actual_mins": 899, "predicted_mins": 899},
    ],
    "delay_distribution": [
        {"bucket": "On Time (0-5m)", "trains": 820, "percentage": 44.5},
        {"bucket": "Minor (6-15m)", "trains": 540, "percentage": 29.3},
        {"bucket": "Moderate (16-30m)", "trains": 280, "percentage": 15.2},
        {"bucket": "Significant (31-60m)", "trains": 135, "percentage": 7.4},
        {"bucket": "Severe (>60m)", "trains": 65, "percentage": 3.6},
    ],
    "prediction_error_by_horizon": [
        {"horizon": "50 km", "raileta_mae": 1.4, "legacy_ntes_mae": 4.8},
        {"horizon": "100 km", "raileta_mae": 2.1, "legacy_ntes_mae": 7.2},
        {"horizon": "250 km", "raileta_mae": 3.2, "legacy_ntes_mae": 11.5},
        {"horizon": "500 km", "raileta_mae": 4.6, "legacy_ntes_mae": 16.9},
        {"horizon": "750 km", "raileta_mae": 5.8, "legacy_ntes_mae": 22.4},
        {"horizon": "1000 km", "raileta_mae": 6.9, "legacy_ntes_mae": 28.1},
    ],
    "average_delay_by_hour": [
        {"hour": "00:00", "avg_delay": 11.2, "congestion": 28},
        {"hour": "03:00", "avg_delay": 14.8, "congestion": 34},
        {"hour": "06:00", "avg_delay": 19.4, "congestion": 62},
        {"hour": "09:00", "avg_delay": 24.6, "congestion": 84},
        {"hour": "12:00", "avg_delay": 15.1, "congestion": 51},
        {"hour": "15:00", "avg_delay": 13.7, "congestion": 47},
        {"hour": "18:00", "avg_delay": 22.8, "congestion": 88},
        {"hour": "21:00", "avg_delay": 17.5, "congestion": 66},
    ],
    "route_performance": [
        {"corridor": "NDLS - BSB (Vande Bharat)", "punctuality": 96.4, "ml_accuracy": 96.8, "avg_delay": 3.2},
        {"corridor": "MAS - MYS (Southern)", "punctuality": 95.1, "ml_accuracy": 95.9, "avg_delay": 4.1},
        {"corridor": "MMCT - NDLS (Western)", "punctuality": 91.2, "ml_accuracy": 94.5, "avg_delay": 9.8},
        {"corridor": "NDLS - RKMP (Central)", "punctuality": 92.8, "ml_accuracy": 95.1, "avg_delay": 7.4},
        {"corridor": "HWH - NDLS (Eastern)", "punctuality": 84.6, "ml_accuracy": 91.8, "avg_delay": 17.5},
        {"corridor": "SBC - NDLS (North-South)", "punctuality": 82.3, "ml_accuracy": 90.4, "avg_delay": 21.2},
    ],
    "prediction_accuracy_trend": [
        {"month": "Apr", "within_5m": 89.2, "within_10m": 94.8},
        {"month": "May", "within_5m": 90.5, "within_10m": 95.4},
        {"month": "Jun", "within_5m": 91.1, "within_10m": 96.0},
        {"month": "Jul", "within_5m": 91.8, "within_10m": 96.3},
        {"month": "Aug", "within_5m": 93.1, "within_10m": 97.1},
        {"month": "Sep", "within_5m": 94.2, "within_10m": 97.8},
    ],
}


def seed_database_if_empty(db: Session):
    existing = db.query(Train).count()
    if existing > 0:
        return

    for t_data in INITIAL_TRAINS:
        stops_data = t_data["stops"]
        train_kwargs = {k: v for k, v in t_data.items() if k != "stops"}
        train_kwargs["last_updated"] = datetime.utcnow()
        train_obj = Train(**train_kwargs)
        db.add(train_obj)
        db.flush()

        for s_data in stops_data:
            stop_obj = StationStop(train_id=train_obj.id, **s_data)
            db.add(stop_obj)

    db.commit()
    print(f"[RailETA DB] Seeded {len(INITIAL_TRAINS)} Indian Railways corridors.")
