"""
Deterministic Demo Data Generator for RailETA (seed=42).
--------------------------------------------------------
NOTE: All datasets generated by this module are explicitly labeled as
`SIMULATED_DEMO_DATA (seed=42)`. They model realistic railway kinematics
(timetable slack recovery, section running times, weather drag, and
junction congestion) without fabricating claims about real Indian Railways
operational performance.
"""

from datetime import datetime, timedelta
from typing import Any, Dict, List
import numpy as np
import pandas as pd

DEMO_DATA_LABEL = "SIMULATED_DEMO_DATA (seed=42)"
DETERMINISTIC_SEED = 42

STATIONS_CATALOG: Dict[str, Dict[str, Any]] = {
    "MMCT": {"name": "Mumbai Central", "lat": 18.9696, "lng": 72.8193, "zone": "WR"},
    "BVI": {"name": "Borivali", "lat": 19.2288, "lng": 72.8569, "zone": "WR"},
    "ST": {"name": "Surat", "lat": 21.2045, "lng": 72.8408, "zone": "WR"},
    "BRC": {"name": "Vadodara Junction", "lat": 22.3106, "lng": 73.1812, "zone": "WR"},
    "RTM": {"name": "Ratlam Junction", "lat": 23.3342, "lng": 75.0488, "zone": "WR"},
    "KOTA": {"name": "Kota Junction", "lat": 25.2238, "lng": 75.8806, "zone": "WCR"},
    "SWM": {"name": "Sawai Madhopur Junction", "lat": 26.0173, "lng": 76.3526, "zone": "WCR"},
    "MTJ": {"name": "Mathura Junction", "lat": 27.4744, "lng": 77.6739, "zone": "NCR"},
    "NDLS": {"name": "New Delhi", "lat": 28.6429, "lng": 77.2191, "zone": "NR"},
    "CNB": {"name": "Kanpur Central", "lat": 26.4539, "lng": 80.3512, "zone": "NCR"},
    "PRYJ": {"name": "Prayagraj Junction", "lat": 25.4448, "lng": 81.8290, "zone": "NCR"},
    "BSB": {"name": "Varanasi Junction", "lat": 25.3273, "lng": 82.9859, "zone": "NR"},
    "HWH": {"name": "Howrah Junction", "lat": 22.5830, "lng": 88.3426, "zone": "ER"},
    "DHN": {"name": "Dhanbad Junction", "lat": 23.7913, "lng": 86.4299, "zone": "ECR"},
    "GAYA": {"name": "Gaya Junction", "lat": 24.8037, "lng": 84.9994, "zone": "ECR"},
    "DDU": {"name": "Pt. DD Upadhyaya Junction", "lat": 25.2785, "lng": 83.1197, "zone": "ECR"},
    "AGC": {"name": "Agra Cantt", "lat": 27.1578, "lng": 77.9899, "zone": "NCR"},
    "GWL": {"name": "Gwalior Junction", "lat": 26.2156, "lng": 78.1818, "zone": "NCR"},
    "VGLJ": {"name": "Virangana Lakshmibai Jhansi", "lat": 25.4484, "lng": 78.5685, "zone": "NCR"},
    "RKMP": {"name": "Rani Kamalapati (Bhopal)", "lat": 23.2167, "lng": 77.4385, "zone": "WCR"},
    "SBC": {"name": "KSR Bengaluru City", "lat": 12.9781, "lng": 77.5695, "zone": "SWR"},
    "GTL": {"name": "Guntakal Junction", "lat": 15.1669, "lng": 77.3765, "zone": "SCR"},
    "BPQ": {"name": "Balharshah Junction", "lat": 19.8511, "lng": 79.3499, "zone": "CR"},
    "NGP": {"name": "Nagpur Junction", "lat": 21.1522, "lng": 79.0888, "zone": "CR"},
    "BPL": {"name": "Bhopal Junction", "lat": 23.2685, "lng": 77.4126, "zone": "WCR"},
    "MAS": {"name": "MGR Chennai Central", "lat": 13.0827, "lng": 80.2707, "zone": "SR"},
    "KPD": {"name": "Katpadi Junction", "lat": 12.9698, "lng": 79.1381, "zone": "SR"},
    "MYS": {"name": "Mysuru Junction", "lat": 12.3168, "lng": 76.6445, "zone": "SWR"},
}

TRAINS_CATALOG: List[Dict[str, Any]] = [
    {
        "train_number": "12951",
        "train_name": "Mumbai Central - New Delhi Tejas Rajdhani Express",
        "train_type": "Rajdhani",
        "zone": "WR / Western Railway",
        "source": "MMCT",
        "destination": "NDLS",
        "status": "Running Late by 12m",
        "max_permissible_speed_kmph": 130.0,
        "total_distance_km": 1384.0,
        "rake_type": "LHB Tejas Smart Coach (22 Coaches)",
        "locomotive": "WAP-7 #37412 (Vadodara Shed)",
        "initial_position": {
            "latitude": 24.5854,
            "longitude": 75.8362,
            "speed": 118.0,
            "delay_minutes": 12.0,
            "distance_covered_km": 798.0,
            "distance_remaining_km": 586.0,
            "previous_station_code": "RTM",
            "next_station_code": "KOTA",
            "weather_condition": "Clear / Light Haze",
            "weather_severity": 0.10,
            "weather_temp_c": 28.5,
            "weather_visibility_km": 9.2,
            "congestion_level": "Moderate (Kota Outer Yard)",
            "congestion_index": 0.28,
        },
        "route_stops": [
            {"seq": 1, "code": "MMCT", "arr": "17:00", "dep": "17:00", "dist": 0.0, "pf": "1", "halt": 0, "sec_mins": 0, "hist_delay": 1.0, "status": "Departed", "delay": 0, "eta": "17:00", "low": "17:00", "high": "17:02", "conf": 99},
            {"seq": 2, "code": "BVI", "arr": "17:22", "dep": "17:24", "dist": 30.0, "pf": "6", "halt": 2, "sec_mins": 22, "hist_delay": 4.0, "status": "Departed", "delay": 3, "eta": "17:25", "low": "17:24", "high": "17:27", "conf": 98},
            {"seq": 3, "code": "ST", "arr": "19:43", "dep": "19:48", "dist": 263.0, "pf": "1", "halt": 5, "sec_mins": 139, "hist_delay": 7.0, "status": "Departed", "delay": 8, "eta": "19:51", "low": "19:48", "high": "19:55", "conf": 96},
            {"seq": 4, "code": "BRC", "arr": "21:06", "dep": "21:16", "dist": 392.0, "pf": "2", "halt": 10, "sec_mins": 78, "hist_delay": 10.0, "status": "Departed", "delay": 14, "eta": "21:20", "low": "21:16", "high": "21:25", "conf": 95},
            {"seq": 5, "code": "RTM", "arr": "15:25", "dep": "15:28", "dist": 653.0, "pf": "4", "halt": 3, "sec_mins": 189, "hist_delay": 13.0, "status": "Departed", "delay": 17, "eta": "15:42", "low": "15:38", "high": "15:46", "conf": 92},
            {"seq": 6, "code": "KOTA", "arr": "18:30", "dep": "18:35", "dist": 920.0, "pf": "1", "halt": 5, "sec_mins": 165, "hist_delay": 11.0, "status": "Approaching", "delay": 12, "eta": "18:42", "low": "18:35", "high": "18:50", "conf": 84},
            {"seq": 7, "code": "SWM", "arr": "19:38", "dep": "19:40", "dist": 1028.0, "pf": "2", "halt": 2, "sec_mins": 63, "hist_delay": 10.0, "status": "Upcoming", "delay": 9, "eta": "19:47", "low": "19:39", "high": "19:56", "conf": 81},
            {"seq": 8, "code": "MTJ", "arr": "21:33", "dep": "21:35", "dist": 1243.0, "pf": "3", "halt": 2, "sec_mins": 113, "hist_delay": 8.0, "status": "Upcoming", "delay": 6, "eta": "21:39", "low": "21:30", "high": "21:49", "conf": 79},
            {"seq": 9, "code": "NDLS", "arr": "23:15", "dep": "23:15", "dist": 1384.0, "pf": "3", "halt": 0, "sec_mins": 100, "hist_delay": 7.0, "status": "Upcoming", "delay": 4, "eta": "23:19", "low": "23:10", "high": "23:28", "conf": 78},
        ],
    },
    {
        "train_number": "22436",
        "train_name": "New Delhi - Varanasi Vande Bharat Express",
        "train_type": "Vande Bharat",
        "zone": "NR / Northern Railway",
        "source": "NDLS",
        "destination": "BSB",
        "status": "On Time",
        "max_permissible_speed_kmph": 130.0,
        "total_distance_km": 759.0,
        "rake_type": "Vande Bharat 2.0 Trainset (16 Coaches)",
        "locomotive": "Distributed Traction EMU (ICF Chennai)",
        "initial_position": {
            "latitude": 26.1542,
            "longitude": 80.8921,
            "speed": 128.0,
            "delay_minutes": 2.0,
            "distance_covered_km": 442.0,
            "distance_remaining_km": 317.0,
            "previous_station_code": "CNB",
            "next_station_code": "PRYJ",
            "weather_condition": "Sunny & Clear",
            "weather_severity": 0.05,
            "weather_temp_c": 31.0,
            "weather_visibility_km": 10.0,
            "congestion_level": "Low (Green Corridor)",
            "congestion_index": 0.14,
        },
        "route_stops": [
            {"seq": 1, "code": "NDLS", "arr": "06:00", "dep": "06:00", "dist": 0.0, "pf": "16", "halt": 0, "sec_mins": 0, "hist_delay": 1.0, "status": "Departed", "delay": 0, "eta": "06:00", "low": "06:00", "high": "06:01", "conf": 99},
            {"seq": 2, "code": "CNB", "arr": "10:08", "dep": "10:10", "dist": 440.0, "pf": "1", "halt": 2, "sec_mins": 248, "hist_delay": 4.0, "status": "Departed", "delay": 3, "eta": "10:11", "low": "10:09", "high": "10:13", "conf": 96},
            {"seq": 3, "code": "PRYJ", "arr": "12:08", "dep": "12:10", "dist": 635.0, "pf": "6", "halt": 2, "sec_mins": 118, "hist_delay": 5.0, "status": "Approaching", "delay": 2, "eta": "12:10", "low": "12:07", "high": "12:14", "conf": 93},
            {"seq": 4, "code": "BSB", "arr": "14:00", "dep": "14:00", "dist": 759.0, "pf": "1", "halt": 0, "sec_mins": 110, "hist_delay": 3.0, "status": "Upcoming", "delay": -1, "eta": "13:59", "low": "13:55", "high": "14:05", "conf": 91},
        ],
    },
    {
        "train_number": "12301",
        "train_name": "Howrah - New Delhi Rajdhani Express (via Gaya)",
        "train_type": "Rajdhani",
        "zone": "ER / Eastern Railway",
        "source": "HWH",
        "destination": "NDLS",
        "status": "Running Late by 24m",
        "max_permissible_speed_kmph": 130.0,
        "total_distance_km": 1451.0,
        "rake_type": "LHB Rajdhani Coach (20 Coaches)",
        "locomotive": "WAP-7 #30588 (Howrah Shed)",
        "initial_position": {
            "latitude": 25.0961,
            "longitude": 83.8542,
            "speed": 104.0,
            "delay_minutes": 24.0,
            "distance_covered_km": 610.0,
            "distance_remaining_km": 841.0,
            "previous_station_code": "GAYA",
            "next_station_code": "DDU",
            "weather_condition": "Mist / High Humidity",
            "weather_severity": 0.35,
            "weather_temp_c": 24.0,
            "weather_visibility_km": 5.4,
            "congestion_level": "High (DDU Outer Junction)",
            "congestion_index": 0.56,
        },
        "route_stops": [
            {"seq": 1, "code": "HWH", "arr": "16:50", "dep": "16:50", "dist": 0.0, "pf": "9", "halt": 0, "sec_mins": 0, "hist_delay": 1.0, "status": "Departed", "delay": 0, "eta": "16:50", "low": "16:50", "high": "16:52", "conf": 99},
            {"seq": 2, "code": "DHN", "arr": "19:55", "dep": "20:00", "dist": 259.0, "pf": "2", "halt": 5, "sec_mins": 185, "hist_delay": 9.0, "status": "Departed", "delay": 14, "eta": "20:09", "low": "20:05", "high": "20:13", "conf": 95},
            {"seq": 3, "code": "GAYA", "arr": "22:19", "dep": "22:22", "dist": 458.0, "pf": "1", "halt": 3, "sec_mins": 139, "hist_delay": 15.0, "status": "Departed", "delay": 26, "eta": "22:45", "low": "22:40", "high": "22:50", "conf": 92},
            {"seq": 4, "code": "DDU", "arr": "01:25", "dep": "01:35", "dist": 661.0, "pf": "4", "halt": 10, "sec_mins": 183, "hist_delay": 18.0, "status": "Approaching", "delay": 24, "eta": "01:49", "low": "01:42", "high": "01:58", "conf": 81},
            {"seq": 5, "code": "PRYJ", "arr": "03:15", "dep": "03:17", "dist": 813.0, "pf": "4", "halt": 2, "sec_mins": 100, "hist_delay": 19.0, "status": "Upcoming", "delay": 20, "eta": "03:35", "low": "03:26", "high": "03:45", "conf": 79},
            {"seq": 6, "code": "CNB", "arr": "05:20", "dep": "05:25", "dist": 1008.0, "pf": "3", "halt": 5, "sec_mins": 123, "hist_delay": 17.0, "status": "Upcoming", "delay": 16, "eta": "05:36", "low": "05:26", "high": "05:47", "conf": 77},
            {"seq": 7, "code": "NDLS", "arr": "10:05", "dep": "10:05", "dist": 1451.0, "pf": "12", "halt": 0, "sec_mins": 280, "hist_delay": 14.0, "status": "Upcoming", "delay": 11, "eta": "10:16", "low": "10:05", "high": "10:28", "conf": 75},
        ],
    },
    {
        "train_number": "12002",
        "train_name": "New Delhi - Rani Kamalapati Shatabdi Express",
        "train_type": "Shatabdi",
        "zone": "NR / Northern Railway",
        "source": "NDLS",
        "destination": "RKMP",
        "status": "Running Late by 6m",
        "max_permissible_speed_kmph": 150.0,
        "total_distance_km": 707.0,
        "rake_type": "LHB Executive Chair Car (18 Coaches)",
        "locomotive": "WAP-5 #30064 (Ghaziabad Shed)",
        "initial_position": {
            "latitude": 26.5412,
            "longitude": 78.0812,
            "speed": 134.0,
            "delay_minutes": 6.0,
            "distance_covered_km": 278.0,
            "distance_remaining_km": 429.0,
            "previous_station_code": "AGC",
            "next_station_code": "GWL",
            "weather_condition": "Clear Sky",
            "weather_severity": 0.05,
            "weather_temp_c": 29.0,
            "weather_visibility_km": 10.0,
            "congestion_level": "Low (Agra-Gwalior High-Speed Block)",
            "congestion_index": 0.18,
        },
        "route_stops": [
            {"seq": 1, "code": "NDLS", "arr": "06:00", "dep": "06:00", "dist": 0.0, "pf": "1", "halt": 0, "sec_mins": 0, "hist_delay": 1.0, "status": "Departed", "delay": 0, "eta": "06:00", "low": "06:00", "high": "06:02", "conf": 99},
            {"seq": 2, "code": "AGC", "arr": "07:50", "dep": "07:55", "dist": 195.0, "pf": "1", "halt": 5, "sec_mins": 110, "hist_delay": 6.0, "status": "Departed", "delay": 8, "eta": "07:58", "low": "07:55", "high": "08:01", "conf": 96},
            {"seq": 3, "code": "GWL", "arr": "09:23", "dep": "09:28", "dist": 313.0, "pf": "1", "halt": 5, "sec_mins": 88, "hist_delay": 7.0, "status": "Approaching", "delay": 6, "eta": "09:29", "low": "09:25", "high": "09:34", "conf": 91},
            {"seq": 4, "code": "VGLJ", "arr": "10:45", "dep": "10:53", "dist": 411.0, "pf": "2", "halt": 8, "sec_mins": 77, "hist_delay": 6.0, "status": "Upcoming", "delay": 4, "eta": "10:49", "low": "10:44", "high": "10:55", "conf": 89},
            {"seq": 5, "code": "RKMP", "arr": "14:40", "dep": "14:40", "dist": 707.0, "pf": "1", "halt": 0, "sec_mins": 227, "hist_delay": 5.0, "status": "Upcoming", "delay": 2, "eta": "14:42", "low": "14:36", "high": "14:49", "conf": 88},
        ],
    },
    {
        "train_number": "12627",
        "train_name": "KSR Bengaluru - New Delhi Karnataka Express",
        "train_type": "Superfast",
        "zone": "SWR / South Western",
        "source": "SBC",
        "destination": "NDLS",
        "status": "Running Late by 31m",
        "max_permissible_speed_kmph": 110.0,
        "total_distance_km": 2410.0,
        "rake_type": "LHB Superfast Express (24 Coaches)",
        "locomotive": "WAP-7 #37209 (Lallaguda Shed)",
        "initial_position": {
            "latitude": 20.6812,
            "longitude": 79.1624,
            "speed": 92.0,
            "delay_minutes": 31.0,
            "distance_covered_km": 1340.0,
            "distance_remaining_km": 1070.0,
            "previous_station_code": "BPQ",
            "next_station_code": "NGP",
            "weather_condition": "Light Rain Showers",
            "weather_severity": 0.30,
            "weather_temp_c": 26.0,
            "weather_visibility_km": 6.8,
            "congestion_level": "Moderate-High (Nagpur Diamond Crossing)",
            "congestion_index": 0.44,
        },
        "route_stops": [
            {"seq": 1, "code": "SBC", "arr": "19:20", "dep": "19:20", "dist": 0.0, "pf": "1", "halt": 0, "sec_mins": 0, "hist_delay": 2.0, "status": "Departed", "delay": 0, "eta": "19:20", "low": "19:20", "high": "19:22", "conf": 99},
            {"seq": 2, "code": "GTL", "arr": "00:05", "dep": "00:10", "dist": 280.0, "pf": "3", "halt": 5, "sec_mins": 285, "hist_delay": 14.0, "status": "Departed", "delay": 17, "eta": "00:22", "low": "00:18", "high": "00:26", "conf": 95},
            {"seq": 3, "code": "BPQ", "arr": "12:50", "dep": "12:55", "dist": 1190.0, "pf": "2", "halt": 5, "sec_mins": 760, "hist_delay": 26.0, "status": "Departed", "delay": 34, "eta": "13:29", "low": "13:24", "high": "13:34", "conf": 90},
            {"seq": 4, "code": "NGP", "arr": "16:07", "dep": "16:12", "dist": 1401.0, "pf": "1", "halt": 5, "sec_mins": 192, "hist_delay": 24.0, "status": "Approaching", "delay": 31, "eta": "16:38", "low": "16:28", "high": "16:49", "conf": 79},
            {"seq": 5, "code": "BPL", "arr": "22:20", "dep": "22:30", "dist": 1791.0, "pf": "2", "halt": 10, "sec_mins": 368, "hist_delay": 22.0, "status": "Upcoming", "delay": 25, "eta": "22:45", "low": "22:34", "high": "22:58", "conf": 76},
            {"seq": 6, "code": "NDLS", "arr": "09:00", "dep": "09:00", "dist": 2410.0, "pf": "5", "halt": 0, "sec_mins": 630, "hist_delay": 20.0, "status": "Upcoming", "delay": 18, "eta": "09:18", "low": "09:05", "high": "09:32", "conf": 74},
        ],
    },
    {
        "train_number": "20607",
        "train_name": "MGR Chennai Central - Mysuru Vande Bharat Express",
        "train_type": "Vande Bharat",
        "zone": "SR / Southern Railway",
        "source": "MAS",
        "destination": "MYS",
        "status": "On Time",
        "max_permissible_speed_kmph": 130.0,
        "total_distance_km": 497.0,
        "rake_type": "Vande Bharat 2.0 Trainset (16 Coaches)",
        "locomotive": "Distributed Traction EMU (ICF Chennai)",
        "initial_position": {
            "latitude": 12.9767,
            "longitude": 78.2145,
            "speed": 115.0,
            "delay_minutes": 0.0,
            "distance_covered_km": 295.0,
            "distance_remaining_km": 202.0,
            "previous_station_code": "KPD",
            "next_station_code": "SBC",
            "weather_condition": "Pleasant & Clear",
            "weather_severity": 0.05,
            "weather_temp_c": 26.5,
            "weather_visibility_km": 10.0,
            "congestion_level": "Low",
            "congestion_index": 0.12,
        },
        "route_stops": [
            {"seq": 1, "code": "MAS", "arr": "05:50", "dep": "05:50", "dist": 0.0, "pf": "7", "halt": 0, "sec_mins": 0, "hist_delay": 1.0, "status": "Departed", "delay": 0, "eta": "05:50", "low": "05:50", "high": "05:51", "conf": 99},
            {"seq": 2, "code": "KPD", "arr": "07:23", "dep": "07:25", "dist": 130.0, "pf": "1", "halt": 2, "sec_mins": 93, "hist_delay": 2.0, "status": "Departed", "delay": 1, "eta": "07:24", "low": "07:22", "high": "07:26", "conf": 97},
            {"seq": 3, "code": "SBC", "arr": "10:15", "dep": "10:20", "dist": 359.0, "pf": "8", "halt": 5, "sec_mins": 170, "hist_delay": 3.0, "status": "Approaching", "delay": 0, "eta": "10:15", "low": "10:12", "high": "10:18", "conf": 95},
            {"seq": 4, "code": "MYS", "arr": "12:20", "dep": "12:20", "dist": 497.0, "pf": "1", "halt": 0, "sec_mins": 120, "hist_delay": 2.0, "status": "Upcoming", "delay": -2, "eta": "12:18", "low": "12:14", "high": "12:23", "conf": 94},
        ],
    },
]


def add_minutes_to_hhmm(hhmm: str, minutes_delta: float) -> str:
    try:
        parts = hhmm.strip().split(":")
        base = datetime(2026, 1, 1, int(parts[0]) % 24, int(parts[1]) % 60)
        shifted = base + timedelta(minutes=int(round(minutes_delta)))
        return shifted.strftime("%H:%M")
    except Exception:
        return hhmm


def generate_historical_training_dataframe(
    n_days: int = 90,
    samples_per_day: int = 60,
    seed: int = DETERMINISTIC_SEED,
) -> pd.DataFrame:
    """
    Generates a deterministic, chronologically ordered dataset of simulated
    historical train runs across `n_days` (default 5,400 samples) for time-based
    train/validation/test splitting.

    Clearly labeled as SIMULATED_DEMO_DATA (seed=42).
    """
    rng = np.random.default_rng(seed)
    start_date = datetime(2026, 6, 1)
    records: List[Dict[str, Any]] = []

    for day_idx in range(n_days):
        curr_date = start_date + timedelta(days=day_idx)
        date_str = curr_date.strftime("%Y-%m-%d")
        day_of_week = curr_date.weekday()

        for _ in range(samples_per_day):
            train_meta = TRAINS_CATALOG[int(rng.integers(0, len(TRAINS_CATALOG)))]
            train_no = train_meta["train_number"]
            route_code = f"{train_meta['source']}-{train_meta['destination']}"
            stops = train_meta["route_stops"]

            # Pick a target station stop (sequence >= 2)
            stop_idx = int(rng.integers(1, len(stops)))
            target_stop = stops[stop_idx]
            station_code = target_stop["code"]

            # Priority factor: Tier 1 recovers more slack per 100 km than Tier 2
            is_tier1 = train_meta["train_type"] in ("Rajdhani", "Vande Bharat", "Shatabdi")
            recovery_rate_per_100km = 4.6 if is_tier1 else 2.1

            # Current position prior to target station
            dist_to_dest = float(rng.uniform(25.0, max(60.0, target_stop["dist"])))
            dist_to_next = float(min(dist_to_dest, rng.uniform(12.0, 180.0)))

            hour = int(rng.integers(0, 24))
            is_peak = 1.0 if (7 <= hour <= 10 or 17 <= hour <= 21) else 0.0
            is_weekend = 1.0 if day_of_week in (5, 6) else 0.0

            weather = float(
                rng.choice([0.05, 0.15, 0.35, 0.65, 0.85], p=[0.58, 0.20, 0.12, 0.07, 0.03])
            )
            congestion = float(
                np.clip(rng.beta(2.2, 3.8) + 0.12 * is_peak + 0.04 * is_weekend, 0.05, 0.95)
            )

            current_delay = float(np.clip(rng.gamma(2.1, 13.0) - 3.0, -5.0, 160.0))
            previous_station_delay = float(
                np.clip(current_delay + rng.normal(1.5, 4.0), -5.0, 170.0)
            )

            base_speed = 115.0 if is_tier1 else 84.0
            current_speed = float(
                np.clip(
                    base_speed * (1.05 - 0.25 * congestion - 0.30 * weather)
                    + rng.normal(0.0, 7.5),
                    25.0,
                    train_meta["max_permissible_speed_kmph"],
                )
            )

            hist_sec_time = float(max(18.0, target_stop["sec_mins"]))
            hist_avg_delay = float(
                np.clip(
                    target_stop["hist_delay"] + 0.18 * current_delay + rng.normal(0.0, 2.5),
                    0.0,
                    120.0,
                )
            )

            # Ground-truth arrival delay physics in simulation:
            # Slack recovery reduces current_delay on clear tracks, while high congestion/weather
            # or low speed adds delay over the remaining distance.
            slack_recovery = (
                (dist_to_dest / 100.0) * recovery_rate_per_100km * (1.0 - 0.85 * congestion)
            )
            speed_deficit = max(0.0, (base_speed - current_speed) / base_speed)
            enroute_penalty = (dist_to_dest / 100.0) * (
                11.5 * congestion + 16.0 * weather + 8.5 * speed_deficit
            ) + 2.2 * is_peak * congestion

            momentum_shift = 0.25 * (current_delay - previous_station_delay)

            actual_arrival_delay = (
                0.74 * current_delay
                + 0.20 * hist_avg_delay
                + momentum_shift
                - slack_recovery
                + enroute_penalty
                + rng.normal(0.0, 1.85)
            )
            actual_arrival_delay = float(np.clip(actual_arrival_delay, -8.0, 240.0))

            scheduled_remaining_mins = (dist_to_dest / max(50.0, base_speed)) * 60.0
            remaining_travel_time = max(
                5.0, scheduled_remaining_mins + (actual_arrival_delay - current_delay)
            )

            records.append(
                {
                    "date": date_str,
                    "train": train_no,
                    "station": station_code,
                    "route": route_code,
                    "sequence": target_stop["seq"],
                    "scheduled_arrival": target_stop["arr"],
                    "actual_arrival": add_minutes_to_hhmm(
                        target_stop["arr"], actual_arrival_delay
                    ),
                    "current_delay": round(current_delay, 2),
                    "current_speed": round(current_speed, 2),
                    "distance_to_next_station": round(dist_to_next, 2),
                    "distance_to_destination": round(dist_to_dest, 2),
                    "historical_section_running_time": round(hist_sec_time, 2),
                    "historical_average_delay": round(hist_avg_delay, 2),
                    "day_of_week": day_of_week,
                    "hour": hour,
                    "weather": round(weather, 3),
                    "congestion": round(congestion, 3),
                    "previous_station_delay": round(previous_station_delay, 2),
                    "actual_arrival_delay": round(actual_arrival_delay, 2),
                    "remaining_travel_time": round(remaining_travel_time, 2),
                    "data_source": DEMO_DATA_LABEL,
                }
            )

    return pd.DataFrame(records)
